# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHL5pQZCKMoBoqXp4_XNBmY-eKyA-

!pipinstalljoblib
# ==========================================
# House Price Prediction + Streamlit UI
# KNN Regressor
# ==========================================

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv("House Price Prediction Dataset.csv")

# Remove ID
df = df.drop("Id", axis=1)

# Save original categories for Streamlit
locations = df["Location"].unique().tolist()
conditions = df["Condition"].unique().tolist()
garages = df["Garage"].unique().tolist()

# Convert categorical columns
df_encoded = pd.get_dummies(df, drop_first=True)

# Features and target
X = df_encoded.drop("Price", axis=1)
y = df_encoded["Price"]

# Scale data for KNN
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train model
model = KNeighborsRegressor(
    n_neighbors=5
)

model.fit(X_scaled, y)

# Save model and columns
joblib.dump(model, "house_price_knn_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

print("Model trained and saved successfully!")


# ===========================
# Create Streamlit App
# ===========================

app_code = """

import streamlit as st
import pandas as pd
import joblib as jb

model = jb.load('house_price_knn_model.pkl')
scaler = jb.load('scaler.pkl')
columns = jb.load('columns.pkl')


st.title("🏠 House Price Prediction")

area = st.slider("Area", 500, 5000, 1500)
bedrooms = st.slider("Bedrooms", 1, 6, 3)
bathrooms = st.slider("Bathrooms", 1, 5, 2)























